<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__1_2_3_4_5_6_7_8_9_10_11_12</name>
   <tag></tag>
   <elementGuidId>b92ad6be-c935-4e8e-b128-da50ae19a7bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.rounded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8ffc780b-2046-4904-b6e8-3905cc54e41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded</value>
      <webElementGuid>bbba7024-9f05-4281-800a-32d5a1d9ebe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>65ec0171-9093-464d-bb3d-084d7865d918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e081b049-cd54-4d06-b2d1-e99779291f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ตู้เสื้อผ้าชำ</value>
      <webElementGuid>2aa52320-7d90-4bfc-a89c-dc7db06b8f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;c1 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;c2 col&quot;]/form[1]/textarea[@class=&quot;rounded&quot;]</value>
      <webElementGuid>08bf37d6-6a0a-4912-8ccc-8dc026b85a47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='']</value>
      <webElementGuid>bfae2eee-2052-4b79-837f-cc52156aca25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/textarea</value>
      <webElementGuid>1f498f4c-5abd-4b5a-9d3d-09084bea0360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='แจ้งรายละเอียดปัญหา'])[1]/following::textarea[1]</value>
      <webElementGuid>d138e1bb-d811-4fb9-9019-a037f3ae7550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รูปภาพสิ่งของชำรุด'])[1]/following::textarea[1]</value>
      <webElementGuid>bcee458f-63af-4fd8-8a3d-eb7090826c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ยืนยัน'])[1]/preceding::textarea[1]</value>
      <webElementGuid>c98bb90e-783c-498e-bc46-d95c619deaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ตู้เสื้อผ้าชำ']/parent::*</value>
      <webElementGuid>0be920ff-54fb-47cc-b5ce-542aa6bd3c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1a1015b8-d4de-4745-a220-ffead65c8bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'ตู้เสื้อผ้าชำ' or . = 'ตู้เสื้อผ้าชำ')]</value>
      <webElementGuid>0a874adf-71ca-4a45-be20-ed4bc57b8910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
