<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>7bc06c49-880a-40d9-b87f-5b3d482765fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.rounded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>16b0e99e-fa03-40f5-8c79-63eec119143f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded</value>
      <webElementGuid>15250bee-c152-4fa4-ad1e-5cc7fad2deff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>08bda602-aacb-42d0-8a7f-a3b557e8ec63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8dbe7003-9c77-41c9-af71-403c6590a53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ตู้เสื้อผ้</value>
      <webElementGuid>fc442ea1-5dfb-4687-9fb4-55bcb4f946ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;c1 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;c2 col&quot;]/form[1]/textarea[@class=&quot;rounded&quot;]</value>
      <webElementGuid>94cb28fc-817f-43cd-a569-6347390665e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='']</value>
      <webElementGuid>f9aa6769-5fa8-469e-af27-366a71be2064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/textarea</value>
      <webElementGuid>1d11aee4-c11d-4629-8e5b-7a9d26410311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='แจ้งรายละเอียดปัญหา'])[1]/following::textarea[1]</value>
      <webElementGuid>710cb4ef-add6-45d6-977e-2cabf93d0671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รูปภาพสิ่งของชำรุด'])[1]/following::textarea[1]</value>
      <webElementGuid>50df023e-26ec-4973-acdf-b3b6a55e99c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ยืนยัน'])[1]/preceding::textarea[1]</value>
      <webElementGuid>1d99d589-c763-4583-b255-736095ceebb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ตู้เสื้อผ้']/parent::*</value>
      <webElementGuid>3a043443-7d60-49e2-9ce0-6d78477bd729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0f41e966-5a18-487a-825b-0284d8ce7277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'ตู้เสื้อผ้' or . = 'ตู้เสื้อผ้')]</value>
      <webElementGuid>1f128d7f-ec8e-45ce-b07d-8c3790590d4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
