<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>7b892b15-8ebe-4687-bb03-6259a743462d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form > button.btn.btn-light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79eba287-1919-4840-bea3-942609b14d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>19367d4b-e176-48e4-99e6-3735783f1a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light</value>
      <webElementGuid>789a0820-bb0e-4c4d-986f-dbc441672961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ยืนยัน</value>
      <webElementGuid>9a23c0c9-2c30-42c4-b739-04d389b04cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;c1 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;c2 col&quot;]/form[1]/button[@class=&quot;btn btn-light&quot;]</value>
      <webElementGuid>c7cbb84d-93ce-4f66-a940-d53a0e147d74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>a7f2a4b6-28e7-4ac1-bf79-90ca8e0b3246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/button</value>
      <webElementGuid>dccedb50-5a7d-42e8-9f82-fb27d2cdb5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='แจ้งรายละเอียดปัญหา'])[1]/following::button[1]</value>
      <webElementGuid>d4fba08b-3890-46c9-b7ea-08b675830449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รูปภาพสิ่งของชำรุด'])[1]/following::button[1]</value>
      <webElementGuid>e8af64eb-ed99-4b51-9fe2-6ddc7795d68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ยืนยัน']/parent::*</value>
      <webElementGuid>c75099ab-e121-48d7-ad59-64a992c717dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/button</value>
      <webElementGuid>c60be808-0638-427c-90e0-acfbe9cb62e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'ยืนยัน' or . = 'ยืนยัน')]</value>
      <webElementGuid>43e4ea19-83d3-430d-b1cd-ea02b6af6dce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
